name: LiteAnnouncer
version: 1.3.4.0
author: TRCStudioDean
main: studio.trc.bukkit.liteannouncer.Main
api-version: 1.13
folia-supported: true
softdepend: [PlaceholderAPI]
commands:
    la:
        description: 'LiteAnnouncer main command.'
        aliases: [liteannouncer]